language: objective-c
osx_image: xcode10.1
branches:
  only:
    - master
notifications:
  email: false
install:
  - brew install clang-format
script:
  - make test_ios SCHEME=audio_ios_tests SDK=iphonesimulator
  - make test_osx SCHEME=audio_mac_tests SDK=macosx
