language: objective-c
osx_image: xcode7.2
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - make setup-coverage
script:
  - make test SCHEME=audio_ios_tests SDK=iphonesimulator
  - make test SCHEME=audio_ios_non_arc_tests SDK=iphonesimulator
  - make test SCHEME=audio_mac_tests SDK=macosx
  - make test SCHEME=audio_mac_non_arc_tests SDK=macosx
after_success:
  - make send-coverage
